variables:
  SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
  GIT_DEPTH: '0'

stages:
  - build
  - test
  - analysis

build:
  stage: build
  image: node:9
  artifacts:
    paths:
      - node_modules
  script:
    - npm install
  only:
    - merge_requests

test:js:
  stage: test
  image: node:9
  dependencies:
    - build
  artifacts:
    paths:
      - coverage
  script:
    - npm run test:codacy-coverage
  only:
    - merge_requests

analysis:sonarcloud:
  stage: analysis
  image:
    name: sonarsource/sonar-scanner-cli:4.2
    entrypoint: ['']
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
