image: node:9

stages:
  - build
  - test

build:
  stage: build
  artifacts:
    paths:
      - node_modules
  script: 

test:
  stage: test
  dependencies:
    - build
  script:
    - npm run test:codacy-coverage

